pipeline{
  agent any
  tools{
    sbt 'sbt-1.9.7'
  }
  stages{
    stage("Checkout"){
      steps{
      echo "accessing the repo"
      checkout scm
      }

    }
    stage("Build"){
      steps{
         echo "Building the jar"
         sh 'sbt clean compile package'
      }
  
  }
}
